


const Cupon = require('../../domain/entities/cupons.entity');

//const OrderModel = require('../../infrastructure/repositories/database/mongo/models/order.model'); // importa el modelo Mongoose


class CuponsService {
    constructor(cuponsRepository) { // ¡Depende de la interfaz!
        this.cuponsRepository = cuponsRepository;
    }
    
    async getAllCupons() {
        return this.cuponsRepository.getAll();
    }

    async getCuponById(id) {
        return this.cuponsRepository.getById(id);
    }

    async createCupon(cuponData) {
        // Aquí podría haber lógica de negocio y validaciones
        const cuponEntity = new Cupon(
            null, // ID is null because it will be generated by the database
            cuponData.id_user,
            cuponData.init_date,
            cuponData.end_date,
            cuponData.value

        );
        return this.cuponsRepository.create(cuponEntity);
    }

        async updateCupon(id, cuponData) {
                const cuponEntity = new Cupon(
                id,
                cuponData.id_user,
                cuponData.init_date,
                cuponData.end_date ,
                cuponData.value,
                );
            return this.cuponsRepository.update(id, cuponEntity);
        }

    async deleteCupon(id) {
        return this.cuponsRepository.delete(id);
    }
}
module.exports = CuponsService;
