const Order = require('../../domain/entities/order.entity');

class OrderService{
    constructor(orderRepository) { // ¡Depende de la interfaz!
        this.orderRepository = orderRepository;
    }
    
    async getAllOrders() {
        return this.orderRepository.getAll();
    }

    async getOrdersById(id) {
        return this.orderRepository.getById(id);
    }

    async createOrders(orderData) {
        // Aquí podría haber lógica de negocio y validaciones
        const orderEntity = new Order(
            null, // ID is null because it will be generated by the database
            orderData.product,
            orderData.description,
            orderData.quantity,
            orderData.price,
            orderData.discount,
            orderData.total
        );
        return this.orderRepository.create(orderEntity);
    }

    async updateOrder(id, orderData) {
        const orderEntity = new Order(
            id,
            orderData.product,
            orderData.description,
            orderData.quantity,
            orderData.price,
            orderData.discount,
            orderData.total
        );
        return this.orderRepository.update(id, orderEntity);
    }

    async deleteOrder(id) {
        return this.orderRepository.delete(id);
    }
}

module.exports = OrderService;